#!/usr/bin/env python3
"""Apply the locked recovery-option discovery/audit triage exactly once."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import yaml

from safety_data.paths import (
    assert_development_path,
    assert_safe_evidence_output,
    require_v3_audit_consumed_or_safe_input,
)
from safety_data.recovery_option_triage import evaluate_recovery_option_triage
from safety_data.schema import GroupedBranchDataset
from scripts.collect_native_grouped_qsafe import (
    _git_commit,
    _prepare_staged_outputs,
    _publish_staged_outputs,
)


_REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
_CANONICAL_PROTOCOL_PATH = (
    _REPOSITORY_ROOT / "config" / "qsafe_recovery_option_triage_v2.yaml"
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    dataset_path = assert_development_path(
        require_v3_audit_consumed_or_safe_input(args.dataset))
    output = assert_development_path(assert_safe_evidence_output(args.output))
    if output.suffix != ".json":
        parser.error("triage report output must use .json")
    if output.exists():
        raise FileExistsError(f"refusing to overwrite output: {output}")
    analyzer_commit = _git_commit()
    protocol_path = assert_development_path(
        require_v3_audit_consumed_or_safe_input(_CANONICAL_PROTOCOL_PATH))
    protocol = yaml.safe_load(protocol_path.read_text(encoding="utf-8"))
    artifact_root = assert_development_path(
        require_v3_audit_consumed_or_safe_input(
            _REPOSITORY_ROOT
            / str(protocol["collection"]["artifact_root"])))
    if not dataset_path.resolve().is_relative_to(artifact_root) or not (
            output.resolve().is_relative_to(artifact_root)):
        raise ValueError(
            f"triage dataset/report must be below locked artifact root "
            f"{artifact_root}")
    cohort_lock_path = assert_development_path(
        require_v3_audit_consumed_or_safe_input(
            artifact_root / str(
                protocol["collection"]["cohort_lock_filename"])))
    cohort_lock = json.loads(cohort_lock_path.read_text(encoding="utf-8"))
    expected_cohort = {
        "schema_version": "qsafe.recovery_option_triage.cohort_lock.v1",
        "protocol_name": protocol["protocol_name"],
        "protocol_file_sha256": _sha256(_CANONICAL_PROTOCOL_PATH),
        "generator_commit": analyzer_commit,
        "source_seeds": protocol["collection"]["source_seeds"],
    }
    if cohort_lock != expected_cohort:
        raise ValueError(
            "triage analyzer/protocol differs from the pre-outcome cohort lock")
    dataset = GroupedBranchDataset.load(dataset_path)
    if dataset.manifest.get("generator_commit") != analyzer_commit:
        raise ValueError("merged triage dataset was not generated by locked commit")
    shards = dataset.manifest.get("shards")
    if not isinstance(shards, list) or len(shards) != 3 or any(
            not isinstance(shard, dict) or shard.get("generator_commit")
            != analyzer_commit for shard in shards):
        raise ValueError("triage dataset must merge exactly three locked leaf shards")
    merged_seeds = sorted(
        seed for shard in shards for seed in shard.get("source_seeds", []))
    if merged_seeds != protocol["collection"]["source_seeds"]:
        raise ValueError("merged triage shard provenance has the wrong source seeds")
    result = evaluate_recovery_option_triage(dataset, protocol)
    if _git_commit() != analyzer_commit:
        raise RuntimeError("analyzer commit/worktree changed during triage audit")

    payload = {
        "schema_version": "qsafe.recovery_option_triage.audit_bundle.v1",
        "analyzer_commit": analyzer_commit,
        "analyzer_worktree_clean": True,
        "protocol_path": str(protocol_path),
        "protocol_file_sha256": _sha256(protocol_path),
        "cohort_lock_path": str(cohort_lock_path),
        "cohort_lock_sha256": _sha256(cohort_lock_path),
        "dataset_path": str(dataset_path),
        "dataset_file_sha256": _sha256(dataset_path),
        "dataset_content_sha256": dataset.manifest["content_sha256"],
        "triage": result,
    }
    staged = _prepare_staged_outputs((output,))
    staging = staged[0][0]
    try:
        staging.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        if _git_commit() != analyzer_commit:
            raise RuntimeError("analyzer commit/worktree changed before publish")
        _publish_staged_outputs(staged)
    finally:
        staging.unlink(missing_ok=True)
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
